/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 19:32:05 GMT 2022
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.FormElement;
import org.jsoup.nodes.XmlDeclaration;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.jsoup.select.Collector;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.jsoup.select.StructuralEvaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Evaluator_ESTest extends Evaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Evaluator.MatchText evaluator_MatchText0 = new Evaluator.MatchText();
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_MatchText0);
      Document document0 = Parser.parse("*tcNv}:OO", "*tcNv}:OO");
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      Document document0 = Document.createShell("QE{]r4O(qA O5VB$");
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("+w", true);
      document0.prependChild(xmlDeclaration0);
      boolean boolean0 = evaluator_IsEmpty0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      Document document0 = new Document(".})(RgY");
      boolean boolean0 = evaluator_IsEmpty0.matches(document0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document document0 = new Document(" ");
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      Element element0 = document0.head();
      element0.after(" ");
      boolean boolean0 = evaluator_IsOnlyOfType0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      Document document0 = new Document("");
      Element element0 = document0.body();
      boolean boolean0 = evaluator_IsOnlyChild0.matches(element0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      Document document0 = Parser.parseBodyFragment(")u``*1D_K`,OV5%}", "zErB~N`a|bkFsMlJ/N5");
      Elements elements0 = document0.select((Evaluator) evaluator_IsOnlyChild0);
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      Document document0 = Parser.parseBodyFragment(">!y-'6N", ">!y-'6N");
      boolean boolean0 = evaluator_IsRoot0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      boolean boolean0 = evaluator_IsRoot0.matches((Element) null, (Element) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zE7B~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zE7B~N`a|bkFsMlJ/N5", attributes0);
      Document document0 = Parser.parse("zE7B~N`a|bkFsMlJ/N5", "zE7B~N`a|bkFsMlJ/N5");
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(evaluator_IsFirstChild0);
      Element element0 = document0.body();
      Element element1 = collector_FirstFinder0.find(formElement0, element0);
      assertNull(element1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = Parser.parse("i", "i");
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(evaluator_IsFirstChild0);
      Element element0 = collector_FirstFinder0.find(document0, document0);
      assertNotNull(element0);
      assertEquals(0, element0.childNodeSize());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Document document0 = Parser.parse("EKL;$=?\"j`{e", "Object must not be null");
      int int0 = evaluator_IsLastOfType0.calculatePosition(document0, document0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Evaluator.IsNthOfType evaluator_IsNthOfType0 = new Evaluator.IsNthOfType(1526, 1526);
      Document document0 = Parser.parseBodyFragment("\"://", "\"://");
      int int0 = evaluator_IsNthOfType0.calculatePosition(document0, document0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      CDataNode cDataNode0 = new CDataNode("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild(97, 97);
      int int0 = evaluator_IsNthLastChild0.calculatePosition(formElement0, formElement0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild((-137190182), (-63161284));
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_IsNthLastChild0);
      Document document0 = Document.createShell("\"OlzNH1Rzv &L2a");
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Evaluator.IsNthOfType evaluator_IsNthOfType0 = new Evaluator.IsNthOfType(0, 0);
      String string0 = evaluator_IsNthOfType0.toString();
      assertEquals(":nth-of-type(0)", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Evaluator.IsNthLastOfType evaluator_IsNthLastOfType0 = new Evaluator.IsNthLastOfType(1, 1);
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("org.jsoup.select.Evaluator$AttributeWithValueEnding", "org.jsoup.select.Evaluator$AttributeWithValueEnding");
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(evaluator_IsNthLastOfType0);
      Element element0 = collector_FirstFinder0.find(document0, document0);
      assertNotNull(element0);
      assertEquals("head", element0.tagName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment(".7l9V\"v-ip %Js!q>", ".7l9V\"v-ip %Js!q>");
      Evaluator.IsNthLastOfType evaluator_IsNthLastOfType0 = new Evaluator.IsNthLastOfType((-2497), (-2497));
      Element element0 = document0.selectFirst((Evaluator) evaluator_IsNthLastOfType0);
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Parser.parse("DOeY:", ",");
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      Evaluator.IsFirstOfType evaluator_IsFirstOfType0 = new Evaluator.IsFirstOfType();
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(evaluator_IsOnlyOfType0);
      Element element0 = collector_FirstFinder0.find(document0, document0);
      assertNotNull(element0);
      
      element0.before("DOeY:");
      boolean boolean0 = evaluator_IsFirstOfType0.matches(element0, element0);
      assertEquals(2, element0.siblingIndex());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Document document0 = Parser.parse(":matchesWholeText(%s)", ":matchesWholeText(%s)");
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(evaluator_IsLastChild0);
      Element element0 = collector_FirstFinder0.find(document0, document0);
      assertNotNull(element0);
      assertEquals(1, element0.siblingIndex());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Document document0 = Parser.parse("|f2#xKByr+C5Yo$", "|f2#xKByr+C5Yo$");
      Elements elements0 = document0.getElementsByIndexEquals(0);
      assertEquals(3, elements0.size());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\"L`-*'5[bE", "\"L`-*'5[bE");
      Elements elements0 = document0.getElementsByIndexGreaterThan((-2563));
      assertEquals(4, elements0.size());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\"L`-*'5bE", "\"L`-*'5bE");
      Elements elements0 = document0.getElementsByIndexGreaterThan(1);
      assertEquals(0, elements0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment(")u``*1D_K`,OV5%}", ")u``*1D_K`,OV5%}");
      Elements elements0 = document0.getElementsByIndexLessThan(3);
      assertEquals(3, elements0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = null;
      try {
        evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("\"", "\"");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("8|=${TA]dn<", "'<'");
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Attribute attribute0 = new Attribute("zErB~N`a|bkFsMlJ/N5", "zErB~N`a|bkFsMlJ/N5");
      attributes0.put(attribute0);
      Pattern pattern0 = Pattern.compile("zErB~N`a|bkFsMlJ/N5");
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching("zErB~N`a|bkFsMlJ/N5", pattern0);
      boolean boolean0 = evaluator_AttributeWithValueMatching0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Element element0 = formElement0.attr("zErB~N`a|bkFsMlJ/N5", true);
      Pattern pattern0 = Pattern.compile("zErB~N`a|bkFsMlJ/N5");
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching("zErB~N`a|bkFsMlJ/N5", pattern0);
      boolean boolean0 = evaluator_AttributeWithValueMatching0.matches(formElement0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Document document0 = new Document("://");
      Pattern pattern0 = Pattern.compile("aAV");
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching("aAV", pattern0);
      boolean boolean0 = evaluator_AttributeWithValueMatching0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Tag tag0 = Tag.valueOf("'\"&l:c/ @r*=\"&l:c/ @r]");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("'\"&l:c/ @r*=\"&l:c/ @r]", "'\"&l:c/ @r*=\"&l:c/ @r]");
      FormElement formElement0 = new FormElement(tag0, "'\"&l:c/ @r*=\"&l:c/ @r]", attributes1);
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("'\"&l:c/ @r*=\"&l:c/ @r]", "'\"&l:c/ @r*=\"&l:c/ @r]");
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      formElement0.attr("zErB~N`a|bkFsMlJ/N5", true);
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("zErB~N`a|bkFsMlJ/N5", "zErB~N`a|bkFsMlJ/N5");
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(formElement0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("4z8QUPy_", "4z8QUPy_");
      Document document0 = Document.createShell(":");
      boolean boolean0 = evaluator_AttributeWithValueContaining0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Attribute attribute0 = new Attribute("zErB~N`a|bkFsMlJ/N5", "zErB~N`a|bkFsMlJ/N5");
      attributes0.put(attribute0);
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("zErB~N`a|bkFsMlJ/N5", "zErB~N`a|bkFsMlJ/N5");
      boolean boolean0 = evaluator_AttributeWithValueEnding0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = new Attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Element element0 = formElement0.attr("zErB~N`a|bkFsMlJ/N5", true);
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("zErB~N`a|bkFsMlJ/N5", "zErB~N`a|bkFsMlJ/N5");
      boolean boolean0 = evaluator_AttributeWithValueEnding0.matches(element0, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("nth-last-child", "nth-last-child");
      Document document0 = new Document("org.jsoup.select.Evaluator$Matches");
      boolean boolean0 = evaluator_AttributeWithValueEnding0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("i", "i");
      Document document0 = Parser.parse("i", "i");
      document0.attr("i", "[i^=i]");
      boolean boolean0 = evaluator_AttributeWithValueStarting0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("rk3#8m<", "rk3#8m<");
      Tag tag0 = Tag.valueOf("rk3#8m<");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("rk3#8m<", "rk3#8m<");
      FormElement formElement0 = new FormElement(tag0, "rk3#8m<", attributes1);
      boolean boolean0 = evaluator_AttributeWithValueStarting0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\"L`-*'5bE", "\"L`-*'5bE");
      Elements elements0 = document0.getElementsByAttributeValueNot("\"Q\"fbwrbcOtp{{", "\"Q\"fbwrbcOtp{{");
      assertEquals(4, elements0.size());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("j4S7N\"&f[}[h", "\r\n\r\n");
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("\r\n\r\n", "\r\n\r\n");
      boolean boolean0 = evaluator_AttributeWithValueNot0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Evaluator.AttributeWithValue evaluator_AttributeWithValue0 = new Evaluator.AttributeWithValue("org.jsoup.parser.ParseErrorList", "org.jsoup.parser.ParseErrorList");
      Tag tag0 = Tag.valueOf("'nth-last-child");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("org.jsoup.parser.ParseErrorList", "org.jsoup.parser.parseerrorlist");
      FormElement formElement0 = new FormElement(tag0, "'nuh-last-child", attributes1);
      boolean boolean0 = evaluator_AttributeWithValue0.matches(formElement0, formElement0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Evaluator.AttributeWithValue evaluator_AttributeWithValue0 = new Evaluator.AttributeWithValue("org.jsoup.parser.ParseErrorList", "org.jsoup.parser.ParseErrorList");
      Tag tag0 = Tag.valueOf("'nh-last-chic(");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("org.jsoup.parser.ParseErrorList", "qT/Aar&cZyj");
      FormElement formElement0 = new FormElement(tag0, "'nuh-last-child", attributes1);
      boolean boolean0 = evaluator_AttributeWithValue0.matches(formElement0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      CDataNode cDataNode0 = new CDataNode("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Element element0 = formElement0.attr("zErB~N`a|bkFsMlJ/N5", true);
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("zErB~N`a|bkFsMlJ/N5");
      boolean boolean0 = evaluator_AttributeStarting0.matches(formElement0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Tag tag0 = Tag.valueOf("zErB~N`a|bkFsMlJ/N5");
      CDataNode cDataNode0 = new CDataNode("zErB~N`a|bkFsMlJ/N5");
      Attributes attributes0 = cDataNode0.attributes();
      FormElement formElement0 = new FormElement(tag0, "zErB~N`a|bkFsMlJ/N5", attributes0);
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("zErB~N`a|bkFsMlJ/N5");
      boolean boolean0 = evaluator_AttributeStarting0.matches(formElement0, formElement0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_AllElements0);
      boolean boolean0 = structuralEvaluator_Not0.matches((Element) null, (Element) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_AllElements0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not(*)", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Evaluator.IsFirstOfType evaluator_IsFirstOfType0 = new Evaluator.IsFirstOfType();
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_IsFirstOfType0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals(":first-of-type ", string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\"L`-*=5bE", "\"L`-*=5bE");
      Document document1 = document0.normalise();
      assertSame(document0, document1);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("'}WjGd_q17V");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_Tag0);
      String string0 = structuralEvaluator_ImmediateParent0.toString();
      assertEquals("'}WjGd_q17V > ", string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Evaluator.ContainsOwnText evaluator_ContainsOwnText0 = new Evaluator.ContainsOwnText("Tv=");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_ContainsOwnText0);
      String string0 = structuralEvaluator_ImmediateParent0.toString();
      assertEquals(":containsOwn(tv=) > ", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("|f2#xKByr+C5Yo$", "|f2#xKByr+C5Yo$");
      Elements elements0 = document0.getElementsContainingOwnText("|f2#xKByr+C5Yo$");
      assertEquals(1, elements0.size());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Evaluator.Attribute evaluator_Attribute0 = new Evaluator.Attribute("'Pm.#R%;_DDl2IjB>G'");
      String string0 = evaluator_Attribute0.toString();
      assertEquals("['Pm.#R%;_DDl2IjB>G']", string0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\"L`-*'5[E", "\"L`-*'5[E");
      Elements elements0 = document0.getElementsByAttribute("\"L`-*'5[E");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith("W1DV");
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_TagEndsWith0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals("W1DV ", string0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith("M{<EM tAdwl]");
      // Undeclared exception!
      try { 
        evaluator_TagEndsWith0.matches((Element) null, (Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Evaluator$TagEndsWith", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IsLastOfType0);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_Not0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals(":not(:last-of-type) ", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Document document0 = Parser.parse("figcaption", ":last-of-type");
      Elements elements0 = document0.select(":last-of-type");
      assertEquals(2, elements0.size());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Evaluator.MatchesWholeOwnText evaluator_MatchesWholeOwnText0 = new Evaluator.MatchesWholeOwnText((Pattern) null);
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_MatchesWholeOwnText0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not(:matchesWholeOwnText(null))", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IsEmpty0);
      Pattern pattern0 = Pattern.compile(" b3jh'#%LKC", (-907));
      Evaluator.MatchesWholeOwnText evaluator_MatchesWholeOwnText0 = new Evaluator.MatchesWholeOwnText(pattern0);
      structuralEvaluator_Not0.evaluator = (Evaluator) evaluator_MatchesWholeOwnText0;
      // Undeclared exception!
      try { 
        structuralEvaluator_Not0.matches((Element) null, (Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Evaluator$MatchesWholeOwnText", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Evaluator.ContainsWholeOwnText evaluator_ContainsWholeOwnText0 = new Evaluator.ContainsWholeOwnText("org.jsoup.select.Evaluator$AttributeWithValueStarting");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_ContainsWholeOwnText0);
      String string0 = structuralEvaluator_ImmediateParent0.toString();
      assertEquals(":containsWholeOwnText(org.jsoup.select.Evaluator$AttributeWithValueStarting) > ", string0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Document document0 = Parser.parse("|f2#xKByr+C5Yo$", "|f2#xKByr+C5Yo$");
      Elements elements0 = document0.select(":containsWholeOwnText(%s)");
      assertEquals(0, elements0.size());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Evaluator.MatchesOwn evaluator_MatchesOwn0 = new Evaluator.MatchesOwn((Pattern) null);
      String string0 = evaluator_MatchesOwn0.toString();
      assertEquals(":matchesOwn(null)", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Document document0 = Parser.parse("^b+^", "^b+^");
      Elements elements0 = document0.getElementsMatchingOwnText("^b+^");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Document document0 = Parser.parse("|f2#xKByr+C5Yo$", "|f2#xKByr+C5Yo$");
      Elements elements0 = document0.getElementsByClass("|f2#xKByr+C5Yo$");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Evaluator.Class evaluator_Class0 = new Evaluator.Class(":not(org.jsoup.select.StructuralEvaluator$Root@1)");
      String string0 = evaluator_Class0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Evaluator.Id evaluator_Id0 = new Evaluator.Id("org.jsoup.select.Evaluator$IsOnlyOfType");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_Id0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(#org.jsoup.select.Evaluator$IsOnlyOfType)", string0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Document document0 = Document.createShell("|f2#xKByr+CcYo$");
      Element element0 = document0.getElementById("|f2#xKByr+CcYo$");
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("K>K");
      Document document0 = Document.createShell(")Ky>S/N<'9");
      boolean boolean0 = evaluator_ContainsData0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("");
      String string0 = evaluator_ContainsData0.toString();
      assertEquals(":containsData()", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Evaluator.IsNthChild evaluator_IsNthChild0 = new Evaluator.IsNthChild(1789, (-3231));
      Document document0 = Document.createShell("6");
      int int0 = evaluator_IsNthChild0.calculatePosition(document0, document0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Evaluator.IsNthChild evaluator_IsNthChild0 = new Evaluator.IsNthChild((-2688), (-2688));
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_IsNthChild0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(:nth-child(-2688n-2688))", string0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Document document0 = Parser.parse("CaZD<mUaz-IMn]", "CaZD<mUaz-IMn]");
      Elements elements0 = document0.getElementsContainingText("CaZD<mUaz-IMn]");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Evaluator.ContainsText evaluator_ContainsText0 = new Evaluator.ContainsText("`,%V");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_ContainsText0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(:contains(`,%v))", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("", (-1690));
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(pattern0);
      String string0 = evaluator_Matches0.toString();
      assertEquals(":matches()", string0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Document document0 = Parser.parse("|f2#xKByr+C5Yo$", "|f2#xKByr+C5Yo$");
      Elements elements0 = document0.getElementsMatchingText("|f2#xKByr+C5Yo$");
      assertEquals(4, elements0.size());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Evaluator.ContainsWholeText evaluator_ContainsWholeText0 = new Evaluator.ContainsWholeText("Must be false");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_ContainsWholeText0);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_ImmediateParent0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals(":containsWholeText(Must be false) >  ", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Evaluator.ContainsWholeText evaluator_ContainsWholeText0 = new Evaluator.ContainsWholeText("?ld/aa:rBKlp|^N5 \"-");
      // Undeclared exception!
      try { 
        evaluator_ContainsWholeText0.matches((Element) null, (Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Evaluator$ContainsWholeText", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("InTableText");
      Evaluator.MatchesWholeText evaluator_MatchesWholeText0 = new Evaluator.MatchesWholeText(pattern0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_MatchesWholeText0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals(":matchesWholeText(InTableText) + ", string0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Document document0 = Document.createShell(":matchesWholeText(%s)");
      boolean boolean0 = document0.is(":matchesWholeText(%s)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Evaluator.AttributeWithValueContaining evaluator_AttributeWithValueContaining0 = new Evaluator.AttributeWithValueContaining("'\"&l:c/ @r*=\"&l:c/ @r]", "'\"&l:c/ @r*=\"&l:c/ @r]");
      String string0 = evaluator_AttributeWithValueContaining0.toString();
      assertEquals("['\"&l:c/ @r*=\"&l:c/ @r]*='\"&l:c/ @r*=\"&l:c/ @r]]", string0);
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IsRoot0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not(:root)", string0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("'[\"']");
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_AttributeStarting0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals("[^'[\"']] ", string0);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      Evaluator.IsOnlyChild evaluator_IsOnlyChild0 = new Evaluator.IsOnlyChild();
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_IsOnlyChild0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals(":only-child ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("[", "[");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueEnding0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals("[[$=[] ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      Evaluator.IsFirstChild evaluator_IsFirstChild0 = new Evaluator.IsFirstChild();
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_IsFirstChild0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals(":first-child + ", string0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("aAV");
      Evaluator.AttributeWithValueMatching evaluator_AttributeWithValueMatching0 = new Evaluator.AttributeWithValueMatching("aAV", pattern0);
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_AttributeWithValueMatching0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not([aav~=aAV])", string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_IsEmpty0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals(":empty ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      Evaluator.MatchText evaluator_MatchText0 = new Evaluator.MatchText();
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_MatchText0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(:matchText)", string0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      Evaluator.IsNthLastOfType evaluator_IsNthLastOfType0 = new Evaluator.IsNthLastOfType((-4583), (-4583));
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IsNthLastOfType0);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_Not0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals(":not(:nth-last-of-type(-4583n-4583)) ", string0);
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_IsOnlyOfType0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(:only-of-type)", string0);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      Evaluator.IndexGreaterThan evaluator_IndexGreaterThan0 = new Evaluator.IndexGreaterThan((-443));
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IndexGreaterThan0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not(:gt(-443))", string0);
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("\"org.jsoup.select.Evaluator$IndexLessThan", "\"org.jsoup.select.Evaluator$IndexLessThan");
      String string0 = evaluator_AttributeWithValueNot0.toString();
      assertEquals("[\"org.jsoup.select.evaluator$indexlessthan!=\"org.jsoup.select.evaluator$indexlessthan]", string0);
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      Evaluator.AttributeWithValue evaluator_AttributeWithValue0 = new Evaluator.AttributeWithValue("Nw~", "Children collection to be inserted must not be null.");
      String string0 = evaluator_AttributeWithValue0.toString();
      assertEquals("[nw~=children collection to be inserted must not be null.]", string0);
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      Document document0 = Parser.parse("\"L`-*'5[bE", "\"L`-*'5[bE");
      Elements elements0 = document0.getElementsByAttributeValue("\"L`-*'5[bE", "\"L`-*'5[bE");
      assertTrue(elements0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("+q4c*e[#RRNh?q==%3s", "+q4c*e[#RRNh?q==%3s");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueStarting0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals("[+q4c*e[#rrnh?q==%3s^=+q4c*e[#rrnh?q==%3s] ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      Evaluator.AttributeWithValueStarting evaluator_AttributeWithValueStarting0 = new Evaluator.AttributeWithValueStarting("rk3#8m<", "rk3#8m<");
      Document document0 = Parser.parse("rk3#8m<", "rk3#8m<");
      boolean boolean0 = evaluator_AttributeWithValueStarting0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      Evaluator.IsNthLastChild evaluator_IsNthLastChild0 = new Evaluator.IsNthLastChild(118813, 0);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_IsNthLastChild0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals(":nth-last-child(118813n) ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_IsLastChild0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals(":last-child + ", string0);
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan((-1846));
      String string0 = evaluator_IndexLessThan0.toString();
      assertEquals(":lt(-1846)", string0);
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      Document document0 = Parser.parse("\"L`-*'5[bE", "\"L`-*'5[bE");
      document0.getElementsByIndexLessThan((-304));
  }

  @Test(timeout = 4000)
  public void test98()  throws Throwable  {
      Evaluator.IndexEquals evaluator_IndexEquals0 = new Evaluator.IndexEquals(0);
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_IndexEquals0);
      String string0 = structuralEvaluator_Not0.toString();
      assertEquals(":not(:eq(0))", string0);
  }
}
