/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 19:32:35 GMT 2022
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Reader;
import java.io.StringReader;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Collector;
import org.jsoup.select.CombiningEvaluator;
import org.jsoup.select.Evaluator;
import org.jsoup.select.StructuralEvaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StructuralEvaluator_ESTest extends StructuralEvaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueEnding0);
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      Document document1 = Document.createShell("@B2q^v&-nvU!cNPM/A4");
      StringReader stringReader0 = new StringReader("%s + ");
      Document document2 = parser0.parseInput((Reader) stringReader0, "[@b2q^v&-nvu!cnpm/a4$=@b2q^v&-nvu!cnpm/a4] ~ ");
      document2.appendTo(document1);
      boolean boolean0 = structuralEvaluator_PreviousSibling0.matches(document0, document2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = new Document((String) null);
      Document document1 = document0.shallowClone();
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData((String) null);
      document0.prependChild(document1);
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_ContainsData0);
      boolean boolean0 = structuralEvaluator_ImmediateParent0.matches(document0, document1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Document document0 = Parser.parse("'0x s03*Vmdy}", "'0x s03*Vmdy}");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_IsLastChild0);
      boolean boolean0 = structuralEvaluator_ImmediateParent0.matches((Element) null, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_IsLastChild0);
      boolean boolean0 = structuralEvaluator_ImmediateParent0.matches((Element) null, (Element) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Document document0 = Parser.parse("'0x s03*Vmdy}", "'0x s03*Vmdy}");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_IsLastChild0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediateParent0);
      boolean boolean0 = structuralEvaluator_Has0.matches((Element) null, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueEnding0);
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StringReader stringReader0 = new StringReader("%s + ");
      Document document1 = parser0.parseInput((Reader) stringReader0, "[@b2q^v&-nvu!cnpm/a4$=@b2q^v&-nvu!cnpm/a4] ~ ");
      Element element0 = document1.appendTo(document1);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_PreviousSibling0);
      // Undeclared exception!
      structuralEvaluator_Parent0.matches(document0, element0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueEnding0);
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      Document document1 = Document.createShell("@B2q^v&-nvU!cNPM/A4");
      Element element0 = document0.appendTo(document1);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_PreviousSibling0);
      boolean boolean0 = structuralEvaluator_Parent0.matches(document1, element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Document document0 = Parser.parse("'0x s03*Vmdy}", "'0x s03*Vmdy}");
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_AllElements0);
      Element element0 = document0.head();
      boolean boolean0 = structuralEvaluator_Parent0.matches(document0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Document document0 = Parser.parse("'0x s03*Vmdy}", "'0x s03*Vmdy}");
      Element element0 = document0.createElement("'0x s03*Vmdy}");
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent(evaluator_IsLastChild0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediateParent0);
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(structuralEvaluator_Has0);
      boolean boolean0 = structuralEvaluator_Parent0.matches(element0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith("3T(v|XqX7Py%{2aZf");
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_TagEndsWith0);
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(structuralEvaluator_Parent0);
      boolean boolean0 = structuralEvaluator_Not0.matches((Element) null, (Element) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Evaluator[] evaluatorArray0 = new Evaluator[4];
      CombiningEvaluator.And combiningEvaluator_And0 = new CombiningEvaluator.And(evaluatorArray0);
      ArrayList<Evaluator> arrayList0 = combiningEvaluator_And0.evaluators;
      CombiningEvaluator.And combiningEvaluator_And1 = new CombiningEvaluator.And(arrayList0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(combiningEvaluator_And1);
      combiningEvaluator_And1.num = (-1336);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediatePreviousSibling0);
      Document document0 = Document.createShell("org.jsoup.helper.HttpConnection$1");
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Evaluator[] evaluatorArray0 = new Evaluator[4];
      CombiningEvaluator.And combiningEvaluator_And0 = new CombiningEvaluator.And(evaluatorArray0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(combiningEvaluator_And0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediatePreviousSibling0);
      Parser parser0 = Parser.xmlParser();
      StringReader stringReader0 = new StringReader("bgY,Kwzy6<;<0");
      Document document0 = parser0.parseInput((Reader) stringReader0, "org.jsoup.helper.HttpConnection$1");
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document document0 = new Document("/~E@5u");
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(structuralEvaluator_Root0);
      boolean boolean0 = structuralEvaluator_Not0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Evaluator[] evaluatorArray0 = new Evaluator[4];
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      evaluatorArray0[1] = (Evaluator) evaluator_AllElements0;
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      evaluatorArray0[2] = (Evaluator) structuralEvaluator_Root0;
      CombiningEvaluator.And combiningEvaluator_And0 = new CombiningEvaluator.And(evaluatorArray0);
      combiningEvaluator_And0.replaceRightMostEvaluator(evaluatorArray0[1]);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(combiningEvaluator_And0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediatePreviousSibling0);
      Document document0 = Document.createShell("org.jsoup.helper.HttpConnection$1");
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_AttributeWithValueEnding0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals("[@b2q^v&-nvu!cnpm/a4$=@b2q^v&-nvu!cnpm/a4] ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Evaluator.IndexLessThan evaluator_IndexLessThan0 = new Evaluator.IndexLessThan(1);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_IndexLessThan0);
      Collector.FirstFinder collector_FirstFinder0 = new Collector.FirstFinder(structuralEvaluator_PreviousSibling0);
      Document document0 = Document.createShell("X");
      Element element0 = collector_FirstFinder0.find(document0, document0);
      assertNotNull(element0);
      assertEquals("body", element0.tagName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(structuralEvaluator_Root0);
      String string0 = structuralEvaluator_Not0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Evaluator.AttributeWithValueEnding evaluator_AttributeWithValueEnding0 = new Evaluator.AttributeWithValueEnding("@B2q^v&-nvU!cNPM/A4", "@B2q^v&-nvU!cNPM/A4");
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_AttributeWithValueEnding0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals("[@b2q^v&-nvu!cnpm/a4$=@b2q^v&-nvu!cnpm/a4] + ", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_IsLastChild0);
      Document document0 = Parser.parse("'0x s03*Vmdy}", "'0x s03*Vmdy}");
      document0.select((Evaluator) structuralEvaluator_ImmediatePreviousSibling0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_Root0);
      String string0 = structuralEvaluator_Has0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Evaluator.TagEndsWith evaluator_TagEndsWith0 = new Evaluator.TagEndsWith("3T(v|XqX7Py%{2aZf");
      StructuralEvaluator.Parent structuralEvaluator_Parent0 = new StructuralEvaluator.Parent(evaluator_TagEndsWith0);
      String string0 = structuralEvaluator_Parent0.toString();
      assertEquals("3T(v|XqX7Py%{2aZf ", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      StructuralEvaluator.ImmediateParent structuralEvaluator_ImmediateParent0 = new StructuralEvaluator.ImmediateParent((Evaluator) null);
      String string0 = structuralEvaluator_ImmediateParent0.toString();
      assertEquals("null > ", string0);
  }
}
