/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 19:15:13 GMT 2022
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.jsoup.SerializationException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SerializationException_ESTest extends SerializationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException("jaX@");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("[8>4`i1+A8h4~'&n");
      SerializationException serializationException0 = new SerializationException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((String) null);
      SerializationException serializationException0 = new SerializationException((String) null, mockThrowable0);
  }
}
