/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 19:29:06 GMT 2022
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.jsoup.UncheckedIOException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UncheckedIOException_ESTest extends UncheckedIOException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UncheckedIOException uncheckedIOException0 = new UncheckedIOException("7CmDT|");
      IOException iOException0 = uncheckedIOException0.ioException();
      assertNotNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UncheckedIOException uncheckedIOException0 = new UncheckedIOException("7CmDT|");
      MockIOException mockIOException0 = (MockIOException)uncheckedIOException0.getCause();
      UncheckedIOException uncheckedIOException1 = new UncheckedIOException(mockIOException0);
      assertFalse(uncheckedIOException1.equals((Object)uncheckedIOException0));
  }
}
