/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 19:29:02 GMT 2022
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseErrorList;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ParseErrorList_ESTest extends ParseErrorList_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseErrorList parseErrorList0 = ParseErrorList.tracking(2825);
      boolean boolean0 = parseErrorList0.canAddError();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseErrorList parseErrorList0 = ParseErrorList.noTracking();
      boolean boolean0 = parseErrorList0.canAddError();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseErrorList parseErrorList0 = ParseErrorList.tracking(0);
      int int0 = parseErrorList0.getMaxSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseErrorList parseErrorList0 = ParseErrorList.noTracking();
      ParseErrorList parseErrorList1 = (ParseErrorList)parseErrorList0.clone();
      assertTrue(parseErrorList1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseErrorList parseErrorList0 = new ParseErrorList(0, 0);
      ParseErrorList parseErrorList1 = new ParseErrorList(parseErrorList0);
      assertEquals(0, parseErrorList1.size());
  }
}
